arrowParens: avoid
plugins:
    - prettier-plugin-tailwindcss
    - prettier-plugin-packagejson
printWidth: 120
singleQuote: true
semi: true
singleAttributePerLine: false
tabWidth: 4
tailwindStylesheet: ./src/styles/globals.css
trailingComma: es5
proseWrap: always
quoteProps: consistent
